version: '3.9'

services:
    humbel_env_zsh:
        build:
            context: .
        image: humbel_env_zsh
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        stdin_open: true
        privileged: true
        tty: true
        network_mode: "host"
        volumes:
            - /etc/timezone:/etc/timezone:ro 
            - /etc/localtime:/etc/localtime:ro \
            - $HOME/dev_ws:/root/dev_ws:rw \
            - /tmp/.X11-unix:/tmp/.X11-unix:rw \
            - $HOME/.Xauthority:/root/.Xauthority:ro \
            - $PWD/.session.yml:/root/.session.yml \
            - $PWD/.tmux.conf:/root/.tmux.conf \
        environment:
            - DISPLAY=$DISPLAY
            - PYTHONBUFFERED=1
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        command: tail -f /dev/null # bash -c "top"
